import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {invoke} from '@tauri-apps/api/core';
import {open,save} from '@tauri-apps/plugin-dialog';
import './styles.css';

type Scenario={id:number;scenario_id:string;name:string;test_step:string;expected_result:string;status:string;favorite:boolean;last_execution?:string};
type Rule={id:number;target:string;operator:string;expected:string;enabled:boolean;result?:boolean;actual?:unknown};
type Resp={status:number;headers:Record<string,string>;body:string;elapsed_ms:number;size:number;timestamp:string;error_type?:string;error?:string};
type Attachment={id:number;file_name:string;description:string;size:number;relative_path:string;created_at:string};
const methods=['GET','POST','PUT','PATCH','DELETE'];
const ops=['equals','not equal','contains','not contains','starts with','ends with','exists','not exists','null','not null','empty','not empty','greater','greater or equal','less','less or equal','regex','type is'];
function buildRequestUrl(raw:string,ps:any[]){try{const u=new URL(raw);ps.filter(p=>p?.enabled&&String(p.key??'').trim()).forEach(p=>u.searchParams.set(String(p.key).trim(),String(p.value??'')));return u.toString()}catch{return raw}}
function safeJson(body:string):any{try{return JSON.parse(body||'{}')}catch{return body||''}}
function displayJson(value:any){return typeof value==='string'?value:JSON.stringify(value,null,2)}
function rows(value:any):Array<{key:string;value:string;type:string}>{if(value===null||value===undefined)return[{key:'value',value:String(value??'null'),type:'null'}];if(typeof value!=='object')return[{key:'value',value:String(value),type:typeof value}];return Object.entries(value).map(([key,v])=>({key,value:typeof v==='object'?JSON.stringify(v):String(v??'null'),type:Array.isArray(v)?'array':typeof v}))}
function JsonTable({value}:{value:any}){return <table className="jsonTable"><thead><tr><th>Key</th><th>Value</th><th>Type</th></tr></thead><tbody>{rows(value).map((r,i)=><tr key={`${r.key}-${i}`}><td>{r.key}</td><td className="jsonValue">{r.value}</td><td>{r.type}</td></tr>)}</tbody></table>}
function App(){
 const [projects,setProjects]=useState<any[]>([]),[project,setProject]=useState<any>(),[scenarios,setScenarios]=useState<Scenario[]>([]),[selected,setSelected]=useState<Scenario>(),[query,setQuery]=useState('');
 const [method,setMethod]=useState('GET'),[url,setUrl]=useState(''),[params,setParams]=useState<any[]>([]),[headers,setHeaders]=useState<any[]>([]),[body,setBody]=useState(''),[auth,setAuth]=useState('No Auth'),[token,setToken]=useState(''),[basicUser,setBasicUser]=useState(''),[basicPass,setBasicPass]=useState(''),[apiKey,setApiKey]=useState('');
 const [rules,setRules]=useState<Rule[]>([]),[selectedRuleIds,setSelectedRuleIds]=useState<number[]>([]),[response,setResponse]=useState<Resp>(),[busy,setBusy]=useState(false),[mock,setMock]=useState(false),[message,setMessage]=useState('');
 const [tab,setTab]=useState<'request'|'response'|'validation'|'history'|'attachments'>('request'),[execs,setExecs]=useState<any[]>([]),[attachments,setAttachments]=useState<Attachment[]>([]),[selectedAttachmentIds,setSelectedAttachmentIds]=useState<number[]>([]);
 const filtered=useMemo(()=>scenarios.filter(s=>`${s.scenario_id} ${s.name}`.toLowerCase().includes(query.toLowerCase())),[scenarios,query]);
 async function load(){try{const p=await invoke<any[]>('list_projects');setProjects(p);if(!project&&p[0]){setProject(p[0]);loadScenarios(p[0].id)}}catch(e){setMessage(String(e))}}
 async function loadScenarios(pid:number){try{const s=await invoke<Scenario[]>('list_scenarios',{projectId:pid});setScenarios(s);if(s[0])selectScenario(s[0])}catch(e){setMessage(String(e))}}
 async function selectScenario(s:Scenario){setSelected(s);setTab('request');setResponse(undefined);setSelectedRuleIds([]);setSelectedAttachmentIds([]);try{const d=await invoke<any>('get_scenario',{scenarioId:s.id});const r=d.request||{};setRules(d.rules||[]);setMethod(r.method||'GET');setUrl(r.url||'');setParams(r.params||[]);setHeaders(r.headers||[]);setBody(r.body||'');setAuth(r.auth||'No Auth');setAttachments(await invoke<Attachment[]>('list_attachments',{scenarioId:s.id}));setExecs(await invoke<any[]>('list_executions',{scenarioId:s.id}))}catch(e){setMessage(String(e))}}
 useEffect(()=>{load()},[]);
 function addParam(){setParams(p=>[...p,{enabled:true,key:'',value:'',kind:'String',description:''}])}function addHeader(){setHeaders(h=>[...h,{enabled:true,key:'',value:''}])}function addRule(){setRules(r=>[...r,{id:Date.now(),target:'body.status',operator:'equals',expected:'',enabled:true}])}
 function removeRule(i:number){setRules(r=>r.filter((_,x)=>x!==i))}function removeSelectedRules(){setRules(r=>r.filter(x=>!selectedRuleIds.includes(x.id)));setSelectedRuleIds([])}
 async function send(){if(!selected||!project)return;setBusy(true);setMessage('');try{const request={method,url:buildRequestUrl(url,params),params:[...params],headers:[...headers],body,auth,token,basicUser,basicPass,apiKey};const r=await invoke<Resp>('execute_request',{request,mock});setResponse(r);setTab('response');const vr=await invoke<any>('validate_response',{scenarioId:selected.id,response:r,rules});setRules(vr.rules||rules);await invoke('save_scenario_request',{scenarioId:selected.id,request});await invoke('record_execution',{projectId:project.id,scenarioId:selected.id,request,response:r,validation:vr});setExecs(await invoke<any[]>('list_executions',{scenarioId:selected.id}));setMessage(vr.final_result||'Request, response, and validation saved')}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 async function importExcel(){if(!project)return;try{const f=await open({filters:[{name:'Excel',extensions:['xlsx']}],multiple:false});if(!f||Array.isArray(f))return;const r=await invoke<any>('inspect_excel',{path:f});const sheet=prompt('Sheet name',r.sheets?.[0]||'Sheet1');if(!sheet)return;const mapping={scenario_id:prompt('Column for scenario number','No')||'No',name:prompt('Column for scenario name','Skenario')||'Skenario',test_step:prompt('Column for test step (optional)','Test Step')||'Test Step',expected_result:prompt('Column for expected result','Expected')||'Expected'};await invoke('import_excel',{projectId:project.id,path:f,sheet,mapping});await loadScenarios(project.id);setMessage('Excel imported')}catch(e){setMessage(String(e))}}
 async function createProject(){const name=prompt('Project name','Customer API UAT');if(!name)return;try{const id=await invoke<number>('create_project',{name,description:''});const p=(await invoke<any[]>('list_projects')).find(x=>x.id===id);if(p){setProject(p);await loadScenarios(id)}}catch(e){setMessage(String(e))}}
 async function addAttachment(){if(!selected)return;try{const f=await open({multiple:true});if(!f)return;for(const path of Array.isArray(f)?f:[f])await invoke('add_attachment',{scenarioId:selected.id,path,description:prompt('Attachment description','')||''});setAttachments(await invoke<Attachment[]>('list_attachments',{scenarioId:selected.id}))}catch(e){setMessage(String(e))}}
 async function removeSelectedAttachments(){try{for(const id of selectedAttachmentIds)await invoke('remove_attachment',{id});setAttachments(a=>a.filter(x=>!selectedAttachmentIds.includes(x.id)));setSelectedAttachmentIds([])}catch(e){setMessage(String(e))}}
 async function exportEvidence(){if(!selected||!execs[0])return;try{const p=await save({defaultPath:`${selected.scenario_id}-evidence.html`,filters:[{name:'HTML',extensions:['html']}]});if(p)await invoke('export_evidence',{executionId:execs[0].id,path:p})}catch(e){setMessage(String(e))}}
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();send()}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[selected,project,method,url,params,headers,body,auth,token,basicUser,basicPass,apiKey,rules,mock]);
 const actualBody=response?safeJson(response.body):undefined;
 return <div className="app"><header><div><b>API UAT Workspace</b><span className="sub">Phase 1 • Local-first UAT execution</span></div><div className="top"><span>{project?.name||'No project'}</span><button onClick={createProject}>New Project</button><button onClick={importExcel} disabled={!project}>Import Excel</button></div></header><main><aside><div className="sideTitle">PROJECTS</div>{projects.map(p=><button key={p.id} className={'project '+(project?.id===p.id?'sel':'')} onClick={()=>{setProject(p);loadScenarios(p.id)}}>{p.name}</button>)}<div className="sideTitle scenarios">SCENARIOS</div><input placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)}/>{filtered.map(s=><button key={s.id} className={'scenario '+(selected?.id===s.id?'sel':'')} onClick={()=>selectScenario(s)}><span>{s.scenario_id}</span><small>{s.status}</small><em>{s.name}</em></button>)}</aside><section className="workspace"><div className="scenarioHead"><div><h2>{selected?.scenario_id||'No scenario selected'}</h2><div>{selected?.name||'Select a scenario to begin'}</div></div>{selected&&<div className="badge">{selected.status}</div>}</div><nav><button className={tab==='request'?'active':''} onClick={()=>setTab('request')}>REQUEST BUILDER</button><button className={tab==='response'?'active':''} onClick={()=>setTab('response')}>RESPONSE</button><button className={tab==='validation'?'active':''} onClick={()=>setTab('validation')}>EXPECTED VS ACTUAL ({rules.length})</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>HISTORY ({execs.length})</button><button className={tab==='attachments'?'active':''} onClick={()=>setTab('attachments')}>ATTACHMENTS ({attachments.length})</button></nav>
 {tab==='request'&&<div className="panel"><div className="sendrow"><select value={method} onChange={e=>setMethod(e.target.value)}>{methods.map(m=><option key={m}>{m}</option>)}</select><input className="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://api.example.com/resource"/><label className="mock"><input type="checkbox" checked={mock} onChange={e=>setMock(e.target.checked)}/> Mock</label><button className="send" onClick={send} disabled={busy||!selected}>{busy?'SENDING...':'SEND'}</button></div><h3>Parameters</h3><table><thead><tr><th>On</th><th>Key</th><th>Value</th><th>Type</th><th>Description</th><th>Action</th></tr></thead><tbody>{params.map((p,i)=><tr key={i}><td><input type="checkbox" checked={!!p.enabled} onChange={e=>setParams(x=>x.map((v,n)=>n===i?{...v,enabled:e.target.checked}:v))}/></td><td><input value={p.key} onChange={e=>setParams(x=>x.map((v,n)=>n===i?{...v,key:e.target.value}:v))}/></td><td><input value={p.value} onChange={e=>setParams(x=>x.map((v,n)=>n===i?{...v,value:e.target.value}:v))}/></td><td>{p.kind}</td><td><input value={p.description||''} onChange={e=>setParams(x=>x.map((v,n)=>n===i?{...v,description:e.target.value}:v))}/></td><td><button className="rowRemove" onClick={()=>setParams(x=>x.filter((_,n)=>n!==i))}>Remove</button></td></tr>)}</tbody></table><button className="link" onClick={addParam}>+ Add parameter</button><h3>Headers</h3><table><thead><tr><th>On</th><th>Key</th><th>Value</th><th>Action</th></tr></thead><tbody>{headers.map((h,i)=><tr key={i}><td><input type="checkbox" checked={!!h.enabled} onChange={e=>setHeaders(x=>x.map((v,n)=>n===i?{...v,enabled:e.target.checked}:v))}/></td><td><input value={h.key} onChange={e=>setHeaders(x=>x.map((v,n)=>n===i?{...v,key:e.target.value}:v))}/></td><td><input type="password" value={h.value} onChange={e=>setHeaders(x=>x.map((v,n)=>n===i?{...v,value:e.target.value}:v))}/></td><td><button className="rowRemove" onClick={()=>setHeaders(x=>x.filter((_,n)=>n!==i))}>Remove</button></td></tr>)}</tbody></table><button className="link" onClick={addHeader}>+ Add header</button><h3>Authentication</h3><div className="auth"><select value={auth} onChange={e=>setAuth(e.target.value)}><option>No Auth</option><option>Bearer Token</option><option>Basic Auth</option><option>API Key</option></select>{auth==='Bearer Token'&&<input type="password" value={token} onChange={e=>setToken(e.target.value)}/>} {auth==='Basic Auth'&&<><input value={basicUser} onChange={e=>setBasicUser(e.target.value)}/><input type="password" value={basicPass} onChange={e=>setBasicPass(e.target.value)}/></>}{auth==='API Key'&&<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)}/>}</div><h3>Body</h3><textarea className="body" value={body} onChange={e=>setBody(e.target.value)}/></div>}
 {tab==='response'&&<div className="panel"><div className="responseMeta">{response?<><b>HTTP {response.status}</b><span>{response.elapsed_ms} ms</span><span>{response.size} bytes</span></>:<span>No response yet</span>}</div>{response?.error&&<div className="errorBox"><b>{response.error_type}</b><div>{response.error}</div></div>}{response&&<><pre className="responseBox">{displayJson(actualBody)}</pre><div className="jsonWrap"><JsonTable value={actualBody}/></div></>}<div className="actionRow"><button onClick={exportEvidence}>Export HTML</button></div></div>}
 {tab==='validation'&&<div className="panel"><div className="rulebar"><div><b>Expected vs Actual</b><div className="hint">Expected diisi manual pada setiap JSON path. Nilai Expected dari Excel tidak digunakan untuk komparasi.</div></div><button onClick={addRule}>+ Add comparison</button><button onClick={removeSelectedRules} disabled={!selectedRuleIds.length} className="rowRemove">Remove selected</button></div><table className="compareTable"><thead><tr><th>Select</th><th>JSON Path</th><th>Expected (manual)</th><th>Actual</th><th>Result</th><th>Action</th></tr></thead><tbody>{rules.map((r,i)=><tr key={r.id||i}><td><input type="checkbox" checked={selectedRuleIds.includes(r.id)} onChange={()=>setSelectedRuleIds(x=>x.includes(r.id)?x.filter(id=>id!==r.id):[...x,r.id])}/></td><td><input value={r.target} onChange={e=>setRules(x=>x.map((v,n)=>n===i?{...v,target:e.target.value}:v))}/></td><td><input value={r.expected} onChange={e=>setRules(x=>x.map((v,n)=>n===i?{...v,expected:e.target.value}:v))}/></td><td className="jsonValue">{r.actual===undefined?'—':displayJson(r.actual)}</td><td>{r.result===undefined?'—':r.result?'PASS':'FAIL'}</td><td><button className="rowRemove" onClick={()=>removeRule(i)}>Remove</button></td></tr>)}</tbody></table><div className="hint">Contoh path: response.status, body.status, body.data.id. Hanya rule yang diaktifkan yang divalidasi.</div></div>}
 {tab==='history'&&<div className="panel">{execs.length?execs.map(e=><div className="execution" key={e.id}><b>Execution #{e.execution_number}</b><span>{e.final_result}</span><small>{e.created_at}</small></div>):<div className="emptyState">No executions yet.</div>}</div>}
 {tab==='attachments'&&<div className="panel"><div className="rulebar"><b>Scenario attachments</b><div><button onClick={addAttachment}>+ Add attachment</button><button onClick={removeSelectedAttachments} disabled={!selectedAttachmentIds.length}>Remove selected</button></div></div>{attachments.length?attachments.map(a=><div className="attachmentRow" key={a.id}><label className="checkboxRow"><input type="checkbox" checked={selectedAttachmentIds.includes(a.id)} onChange={()=>setSelectedAttachmentIds(x=>x.includes(a.id)?x.filter(id=>id!==a.id):[...x,a.id])}/>{a.file_name}</label><div>{a.description}</div></div>):<div className="emptyState">No attachments yet.</div>}</div>}
 {message&&<div className="toast">{message}</div>}</section></main><footer>Local data • Native HTTP • No telemetry</footer></div>}
createRoot(document.getElementById('root')!).render(<App/>);
