import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {invoke} from '@tauri-apps/api/core';
import {open,save} from '@tauri-apps/plugin-dialog';
import './styles.css';

type Scenario={id:number;scenario_id:string;name:string;test_step:string;expected_result:string;status:string;favorite:boolean;last_execution?:string};
type Rule={id:number;target:string;operator:string;expected:string;enabled:boolean};
type Resp={status:number;headers:Record<string,string>;body:string;elapsed_ms:number;size:number;timestamp:string;error_type?:string;error?:string};
type Attachment={id:number;file_name:string;description:string;size:number;relative_path:string;created_at:string};
const methods=['GET','POST','PUT','PATCH','DELETE'];
const ops=['equals','not equal','contains','not contains','starts with','ends with','exists','not exists','null','not null','empty','not empty','greater','greater or equal','less','less or equal','regex','type is'];
const mask=(k:string,v:string)=>/authorization|cookie|set-cookie|api[-_]?key|token|password|secret/i.test(k)?'********':v;
function App(){
 const [projects,setProjects]=useState<any[]>([]),[project,setProject]=useState<any>(),[scenarios,setScenarios]=useState<Scenario[]>([]),[selected,setSelected]=useState<Scenario>(),[query,setQuery]=useState('');
 const [method,setMethod]=useState('GET'),[url,setUrl]=useState(''),[params,setParams]=useState<any[]>([]),[headers,setHeaders]=useState<any[]>([]),[body,setBody]=useState(''),[auth,setAuth]=useState('No Auth'),[token,setToken]=useState(''),[basicUser,setBasicUser]=useState(''),[basicPass,setBasicPass]=useState(''),[apiKey,setApiKey]=useState('');
 const [rules,setRules]=useState<Rule[]>([]),[response,setResponse]=useState<Resp>(),[busy,setBusy]=useState(false),[mock,setMock]=useState(false),[message,setMessage]=useState(''),[tab,setTab]=useState<'request'|'response'|'validation'|'history'|'attachments'>('request'),[execs,setExecs]=useState<any[]>([]),[attachments,setAttachments]=useState<Attachment[]>([]);
 const filtered=useMemo(()=>scenarios.filter(s=>(s.scenario_id+' '+s.name).toLowerCase().includes(query.toLowerCase())),[scenarios,query]);
 async function load(){try{const p=await invoke<any[]>('list_projects');setProjects(p);if(!project&&p[0]){setProject(p[0]);loadScenarios(p[0].id)}}catch(e){setMessage(String(e))}}
 async function loadScenarios(pid:number){const s=await invoke<Scenario[]>('list_scenarios',{projectId:pid});setScenarios(s);if(s[0]) selectScenario(s[0])}
 async function selectScenario(s:Scenario){setSelected(s);setTab('request');setResponse(undefined);setAttachments([]);try{const d=await invoke<any>('get_scenario',{scenario_id:s.id});setRules(d.rules||[]);await invoke<Attachment[]>('list_attachments',{scenarioId:s.id}).then(setAttachments);if(d.request){setMethod(d.request.method||'GET');setUrl(d.request.url||'');setParams(d.request.params||[]);setHeaders(d.request.headers||[]);setBody(d.request.body||'');setAuth(d.request.auth||'No Auth')}}catch(e){setMessage(String(e))}}
 useEffect(()=>{load()},[]);
 async function createProject(){const name=prompt('Project name','Customer API UAT');if(!name)return;const id=await invoke<number>('create_project',{name,description:''});await load();const p=(await invoke<any[]>('list_projects')).find(x=>x.id===id);if(p){setProject(p);loadScenarios(id)}}
 async function importExcel(){if(!project)return;try{const f=await open({filters:[{name:'Excel',extensions:['xlsx']}],multiple:false});if(!f||Array.isArray(f))return;const r=await invoke<any>('inspect_excel',{path:f});const sheet=prompt('Sheet name',r.sheets[0]);if(!sheet)return;const map=prompt('Column mapping JSON',JSON.stringify({scenario_id:'Scenario ID',name:'Scenario',test_step:'Test Step',expected_result:'Expected Result'}));if(!map)return;await invoke('import_excel',{project_id:project.id,path:f,sheet,mapping:JSON.parse(map)});await loadScenarios(project.id);setMessage('Excel imported')}catch(e){setMessage(String(e))}}
 function addParam(){setParams([...params,{enabled:true,key:'',value:'',kind:'String',description:''}])};function addHeader(){setHeaders([...headers,{enabled:true,key:'',value:''}])};function addRule(){setRules([...rules,{id:0,target:'body.status',operator:'equals',expected:'SUCCESS',enabled:true}])}
 async function send(){if(!selected)return;setBusy(true);setMessage('');try{const r=await invoke<Resp>('execute_request',{request:{method,url,params,headers,body,auth,token,basicUser,basicPass,apiKey},mock});setResponse(r);setTab('response');const vr=await invoke<any>('validate_response',{scenarioId:selected.id,response:r,rules});setRules(vr.rules);await invoke('save_scenario_request',{scenario_id:selected.id,request:{method,url,params,headers,body,auth,token,basicUser,basicPass,apiKey}});await invoke('record_execution',{project_id:project.id,scenario_id:selected.id,request:{method,url,params,headers,body,auth,token,basicUser,basicPass,apiKey},response:r,validation:vr});setMessage(vr.final_result||r.error_type||'Execution complete');setExecs(await invoke<any[]>('list_executions',{scenario_id:selected.id}));await loadScenarios(project.id)}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 async function addAttachment(){if(!selected)return;try{const f=await open({multiple:true});if(!f)return;const files=Array.isArray(f)?f:[f];for(const path of files){const description=prompt(`Description for ${path.split(/[\\/]/).pop()||'attachment'}`,'');await invoke<Attachment>('add_attachment',{scenario_id:selected.id,path,description:description||''})}setAttachments(await invoke<Attachment[]>('list_attachments',{scenario_id:selected.id}));setMessage(`${files.length} attachment(s) added`)}catch(e){setMessage(String(e))}}
 async function updateAttachment(a:Attachment){try{await invoke('update_attachment_description',{id:a.id,description:a.description});setMessage('Attachment description saved')}catch(e){setMessage(String(e))}}
 async function removeAttachment(id:number){try{await invoke('remove_attachment',{id});setAttachments(attachments.filter(a=>a.id!==id));setMessage('Attachment removed')}catch(e){setMessage(String(e))}}
 async function exportEvidence(){if(!selected||!response)return;try{const p=await save({defaultPath:`${selected.scenario_id}-evidence.html`,filters:[{name:'HTML',extensions:['html']}]});if(!p)return;await invoke('export_evidence',{execution_id:execs[0]?.id||0,path:p})}catch(e){setMessage(String(e))}}
 useEffect(()=>{if(selected)invoke<any[]>('list_executions',{scenario_id:selected.id}).then(setExecs).catch(()=>{})},[selected]);
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();send()} if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='e'){e.preventDefault();exportEvidence()}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[selected,method,url,params,headers,body,auth,token,basicUser,basicPass,apiKey,rules,mock]);
 return <div className="app"><header><div><b>API UAT Workspace</b><span className="sub">Phase 1 • Local-first UAT execution</span></div><div className="top">{project?.name||'No project'} <button onClick={createProject}>New Project</button><button onClick={importExcel} disabled={!project}>Import Excel</button></div></header>
 <main><aside><div className="sideTitle">PROJECTS</div>{projects.map(p=><button className={'project '+(project?.id===p.id?'sel':'')} onClick={()=>{setProject(p);loadScenarios(p.id)}} key={p.id}>{p.name}</button>)}<div className="sideTitle scenarios">SCENARIOS</div><input placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)}/>{filtered.map(s=><button className={'scenario '+(selected?.id===s.id?'sel':'')} onClick={()=>selectScenario(s)} key={s.id}><span>{s.scenario_id}</span><small>{s.status}</small><em>{s.name}</em></button>)}</aside>
 <section className="workspace"><div className="scenarioHead"><div><h2>{selected?selected.scenario_id:'No scenario selected'}</h2><div>{selected?.name||'Select a scenario to begin'}</div></div>{selected&&<div className={'badge '+(selected.status==='PASS'?'pass':selected.status==='FAIL'?'fail':'')}>{selected.status}</div>}</div>
 <nav><button className={tab==='request'?'active':''} onClick={()=>setTab('request')}>REQUEST BUILDER</button><button className={tab==='response'?'active':''} onClick={()=>setTab('response')}>RESPONSE</button><button className={tab==='validation'?'active':''} onClick={()=>setTab('validation')}>VALIDATION ({rules.length})</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>HISTORY ({execs.length})</button><button className={tab==='attachments'?'active':''} onClick={()=>setTab('attachments')}>ATTACHMENTS ({attachments.length})</button></nav>
 {tab==='request'&&<div className="panel"><div className="sendrow"><select value={method} onChange={e=>setMethod(e.target.value)}>{methods.map(m=><option key={m}>{m}</option>)}</select><input className="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://api.example.com/customer/detail"/><label className="mock"><input type="checkbox" checked={mock} onChange={e=>setMock(e.target.checked)}/> MOCK</label><button className="send" onClick={send} disabled={busy||!selected}>{busy?'SENDING…':'SEND  ⌘↵'}</button></div>
 <h3>Parameters</h3><table><thead><tr><th>On</th><th>Key</th><th>Value</th><th>Type</th><th>Description</th></tr></thead><tbody>{params.map((p,i)=><tr key={i}><td><input type="checkbox" checked={p.enabled} onChange={e=>{const x=[...params];x[i].enabled=e.target.checked;setParams(x)}}/></td><td><input value={p.key} onChange={e=>{const x=[...params];x[i].key=e.target.value;setParams(x)}}/></td><td><input value={p.value} onChange={e=>{const x=[...params];x[i].value=e.target.value;setParams(x)}}/></td><td><select value={p.kind} onChange={e=>{const x=[...params];x[i].kind=e.target.value;setParams(x)}}><option>String</option><option>Number</option><option>Boolean</option><option>JSON</option></select></td><td><input value={p.description} onChange={e=>{const x=[...params];x[i].description=e.target.value;setParams(x)}}/></td></tr>)}</tbody></table><button className="link" onClick={addParam}>+ Add parameter</button>
 <h3>Headers</h3><table><thead><tr><th>On</th><th>Key</th><th>Value</th></tr></thead><tbody>{headers.map((p,i)=><tr key={i}><td><input type="checkbox" checked={p.enabled} onChange={e=>{const x=[...headers];x[i].enabled=e.target.checked;setHeaders(x)}}/></td><td><input value={p.key} onChange={e=>{const x=[...headers];x[i].key=e.target.value;setHeaders(x)}}/></td><td><input type="password" value={p.value} onChange={e=>{const x=[...headers];x[i].value=e.target.value;setHeaders(x)}}/></td></tr>)}</tbody></table><button className="link" onClick={addHeader}>+ Add header</button>
 <h3>Authentication</h3><div className="auth"><select value={auth} onChange={e=>setAuth(e.target.value)}><option>No Auth</option><option>Bearer Token</option><option>Basic Auth</option><option>API Key</option></select>{auth==='Bearer Token'&&<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Bearer token"/>}{auth==='Basic Auth'&&<><input value={basicUser} onChange={e=>setBasicUser(e.target.value)} placeholder="Username"/><input type="password" value={basicPass} onChange={e=>setBasicPass(e.target.value)} placeholder="Password"/></>}{auth==='API Key'&&<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="API key"/>}</div>
 <h3>Body</h3><select value={body===''?'None':'Raw JSON'} onChange={e=>{if(e.target.value==='None')setBody('')}}><option>None</option><option>Raw JSON</option></select><textarea className="body" value={body} onChange={e=>setBody(e.target.value)} placeholder={"{\n  \"customerId\": 123456\n}"}/>
 </div>}
 {tab==='response'&&<div className="panel"><div className="responseMeta">{response?<><b>HTTP {response.status}</b><span>{response.elapsed_ms} ms</span><span>{response.size} bytes</span><span>{response.timestamp}</span></>:<span>No response yet.</span>}</div>{response?.error_type&&<div className="errorbox"><b>{response.error_type}</b><div>{response.error}</div></div>}<pre className="response">{response?.body||''}</pre>{response&&<><button onClick={exportEvidence}>EXPORT HTML EVIDENCE</button><button onClick={async()=>{if(!response||!selected)return;const p=await save({defaultPath:`${selected.scenario_id}-evidence.json`,filters:[{name:'JSON',extensions:['json']}]});if(p)await invoke('export_evidence_json',{execution_id:execs[0]?.id||0,path:p})}}>EXPORT JSON</button></>}</div>}
 {tab==='validation'&&<div className="panel"><div className="rulebar"><b>Code-free validation</b><button onClick={addRule}>+ Add rule</button></div>{rules.map((r,i)=><div className="rule" key={i}><input value={r.target} onChange={e=>{const x=[...rules];x[i]={...x[i],target:e.target.value};setRules(x)}}/><select value={r.operator} onChange={e=>{const x=[...rules];x[i]={...x[i],operator:e.target.value};setRules(x)}}>{ops.map(o=><option key={o}>{o}</option>)}</select><input value={r.expected} onChange={e=>{const x=[...rules];x[i]={...x[i],expected:e.target.value};setRules(x)}}/><span>—</span><b>{(r as any).result===true?'✓':(r as any).result===false?'✗':'•'}</b><small>{(r as any).actual!==undefined?`Actual: ${JSON.stringify((r as any).actual)}`:''}</small></div>)}<div className="hint">Targets: response.status, body.status, body.data.id. Rules are evaluated natively; HTTP status alone never implies PASS.</div></div>}
 {tab==='attachments'&&<div className="panel"><div className="rulebar"><div><b>Scenario evidence attachments</b><div className="hint">Attachments belong to this scenario and are included in exported evidence for its executions.</div></div><button onClick={addAttachment} disabled={!selected}>+ Add attachment</button></div>{attachments.length===0?<div className="empty">No attachments for this scenario yet.</div>:attachments.map(a=><div className="attachmentRow" key={a.id}><div className="attachmentMeta"><b>{a.file_name}</b><small>{a.size.toLocaleString()} bytes • {a.created_at}</small></div><textarea value={a.description} onChange={e=>setAttachments(attachments.map(x=>x.id===a.id?{...x,description:e.target.value}:x))} placeholder="Describe why this attachment is relevant to UAT evidence…"/><div><button onClick={()=>updateAttachment(a)}>Save description</button><button onClick={()=>removeAttachment(a.id)}>Remove</button></div></div>)}</div>}
 {tab==='history'&&<div className="panel">{execs.length===0?<div>No executions yet.</div>:execs.map((e:any,i)=><div className="execution" key={e.id}><b>Execution #{e.execution_number}</b><span>{e.final_result}</span><small>{e.created_at}</small><button onClick={()=>invoke('export_evidence',{execution_id:e.id,path:''}).catch(()=>{})}>DETAILS</button></div>)}</div>}
 {message&&<div className="toast">{message}</div>}</section></main><footer>Local data • Native HTTP • No telemetry</footer></div>}
createRoot(document.getElementById('root')!).render(<App/>);
